---
version: 2
jobs:
  sync_drupalorg:
    docker:
      - image: nicksantamaria/circleci-drupal-kms-encrypt:latest
    working_directory: /data
    environment:
      GIT_MIRROR_URL: nickurbits@git.drupal.org:sandbox/nickurbits/2923717.git
    steps:
      - checkout
      - run:
          name: Add drupal.org git remote
          command: git remote add drupal "${GIT_MIRROR_URL}"
      - run:
          name: Push to drupal.org git remote
          command: git push --tags drupal "${CIRCLE_BRANCH}"
  lint:
    docker:
      - image: nicksantamaria/circleci-drupal-kms-encrypt:latest
    working_directory: /data
    steps:
      - checkout
      - run:
          name: Ensure yaml files are valid
          command: yamllint /data
      - run:
          name: Ensure json files are valid
          command: cat /data/composer.json | jq .
      - run:
          name: Ensure PHP meets Drupal code standards
          command: |
            phpcs \
              --standard=Drupal \
              --extensions=php,module,inc,install,test,profile,theme,css,info \
              --ignore=*.md \
              /data

workflows:
  version: 2
  main:
    jobs:
      - lint
  sync:
    jobs:
      - sync_drupalorg:
          filters:
            tags:
              only: /.*/
            branches:
              only: /[7-9].x-.*/
